# Generated by Django 4.0.1 on 2022-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='numfin',
            field=models.CharField(max_length=6, unique=True, verbose_name='Numero Final'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='numini',
            field=models.CharField(max_length=6, unique=True, verbose_name='Numero inicial'),
        ),
    ]
