# Generated by Django 4.0.4 on 2022-05-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0003_alter_impguias_cliente_alter_impguias_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='numfin',
            field=models.IntegerField(max_length=6, unique=True, verbose_name='Numero Final'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='numini',
            field=models.IntegerField(max_length=6, unique=True, verbose_name='Numero inicial'),
        ),
    ]
