# Generated by Django 4.0.1 on 2022-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo_combustible',
            field=models.IntegerField(choices=[[0, 'REGULAR'], [1, 'SUPER'], [2, 'DIESEL']], verbose_name='Tipo de Combustible'),
        ),
    ]
