# Generated by Django 4.0.1 on 2022-02-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_tarifario_options_remove_tarifario_tipo_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='placa',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='muni',
            field=models.CharField(help_text='Nombre Municipio', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ruta',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
