# Generated by Django 4.0.1 on 2022-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_vendedor_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
