# Generated by Django 4.0.1 on 2022-02-04 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_alter_vendedor_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre',
            new_name='nombrecom',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='rutadestin',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='razonsoc',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Razon Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='depto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.departamento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.municipio'),
        ),
    ]
