# Generated by Django 4.0.1 on 2022-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0012_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
