# Generated by Django 4.0.1 on 2022-02-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0017_ingreso_guias_codigo_desti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso_guias',
            name='rutades',
            field=models.CharField(default=1, max_length=3, verbose_name='Ruta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingreso_guias',
            name='destino',
            field=models.CharField(max_length=50, verbose_name='Codigo Destino'),
        ),
        migrations.AlterField(
            model_name='ingreso_guias',
            name='origen',
            field=models.CharField(max_length=50, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='ingreso_guias',
            name='ruta',
            field=models.CharField(max_length=3, verbose_name='Ruta'),
        ),
    ]
