# Generated by Django 4.0.1 on 2022-04-20 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0029_correlativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='tipo_envio',
        ),
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='totenv',
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='totpieenv',
            field=models.IntegerField(default=0, verbose_name='Total Envios'),
        ),
        migrations.CreateModel(
            name='Productodet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('peso', models.FloatField(default=0, verbose_name='Peso')),
                ('precio', models.FloatField(default=0, verbose_name='Tarifa')),
                ('totenv', models.FloatField(default=0, verbose_name='Total Envio')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.ingreso_guias')),
                ('tipo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.tarifario')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
