# Generated by Django 4.0.1 on 2022-02-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifario',
            options={'verbose_name_plural': 'Tarifarios'},
        ),
        migrations.RemoveField(
            model_name='tarifario',
            name='tipo_envio',
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('depto', 'ruta', 'piloto')},
        ),
    ]
