# Generated by Django 4.0 on 2022-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='fechacrea',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='fechaingre',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='observa',
            field=models.TextField(verbose_name='Oboservaciones'),
        ),
    ]
