# Generated by Django 4.0.1 on 2022-02-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_remove_vendedor_placa_alter_municipio_muni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
