# Generated by Django 4.0 on 2022-01-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_remove_vendedor_foto_remove_vendedor_porcentaj2'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadeposito',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso_bodega',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='municipios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pilotos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
