# Generated by Django 4.0 on 2022-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_boletadeposito_estado_clientes_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
