# Generated by Django 4.0.1 on 2022-01-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_alter_vendedor_options_alter_vendedor_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
    ]
