# Generated by Django 4.0.1 on 2022-01-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_alter_departamento_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='codigo',
        ),
    ]
