# Generated by Django 4.0.1 on 2022-01-27 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0008_remove_departamento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('muni', models.CharField(help_text='Nombre Municipio', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.AddField(
            model_name='municipio',
            name='depto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.departamento'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
