# Generated by Django 4.0.1 on 2022-01-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_municipio_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='muni',
            field=models.CharField(help_text='Nombre Municipio', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('depto', 'muni')},
        ),
    ]
