# Generated by Django 4.0.1 on 2022-02-05 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_remove_clientes_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='link.vendedor'),
            preserve_default=False,
        ),
    ]
