# Generated by Django 4.0.1 on 2022-02-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_clientes_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
