# Generated by Django 4.0.1 on 2022-01-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0011_alter_boletadeposito_uc_alter_boletadeposito_um_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='deptodesti',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='distancia',
        ),
        migrations.AlterField(
            model_name='rutas',
            name='depto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.departamento'),
        ),
    ]
