# Generated by Django 4.0.1 on 2022-01-31 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0012_remove_rutas_deptodesti_remove_rutas_distancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('ruta', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('vendedor', models.CharField(max_length=15)),
                ('placa', models.CharField(max_length=15)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.departamento')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rutas',
                'unique_together': {('depto', 'ruta')},
            },
        ),
        migrations.AlterField(
            model_name='ingreso_bodega',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='link.ruta', verbose_name='Ruta Entrega'),
        ),
        migrations.DeleteModel(
            name='Rutas',
        ),
    ]
