# Generated by Django 4.0.1 on 2022-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0013_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fpago',
            field=models.IntegerField(choices=[[0, 'POR COBRAR'], [1, 'CONTADO'], [2, 'CREDITO'], [3, 'PREPAGO'], [4, 'CONTRA ENTREGA'], [5, 'CREDITO X COBRAR'], [6, 'CONTADO X COBRAR']], default=1, verbose_name='FORMA DE PAGO'),
            preserve_default=False,
        ),
    ]
