# Generated by Django 4.0.1 on 2022-02-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0014_clientes_fpago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
