# Generated by Django 4.0.1 on 2022-02-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0016_alter_clientes_depto_alter_clientes_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso_guias',
            name='codigo_desti',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingreso_guias',
            name='no_manifiesto',
            field=models.CharField(max_length=5),
        ),
    ]
