# Generated by Django 4.0.1 on 2022-02-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0018_ingreso_guias_rutades_alter_ingreso_guias_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso_guias',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
