# Generated by Django 4.0.1 on 2022-02-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0020_ingreso_guias_boleta_cte_ingreso_guias_comision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso_guias',
            options={'verbose_name': 'Ingreso Guia', 'verbose_name_plural': 'Ingresos Guias'},
        ),
    ]
