# Generated by Django 4.0.1 on 2022-02-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0023_alter_ingreso_guias_boleta_cte_and_more'),
        ('link', '0023_alter_ingreso_guias_codigo_cliente'),
    ]

    operations = [
    ]
