# Generated by Django 4.0.1 on 2022-02-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0024_merge_20220212_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso_guias',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='cliente',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso_guias',
            name='codigo',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
