# Generated by Django 4.0.1 on 2022-02-13 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0025_remove_ingreso_guias_nombre_ingreso_guias_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_hijas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('guia_hija', models.CharField(max_length=10, verbose_name='Guia Hija')),
                ('guia_madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.ingreso_guias')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Hija',
                'verbose_name_plural': 'Ingresos Hijas',
            },
        ),
    ]
