# Generated by Django 4.0.1 on 2022-04-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0031_rename_productodet_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='guia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='link_producto', to='link.ingreso_guias'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ingreso_guias',
            table='link_ingreso_guias',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='link_producto',
        ),
    ]
