# Generated by Django 4.0.1 on 2022-04-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0032_alter_producto_guia_alter_ingreso_guias_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productodet', to='link.ingreso_guias'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productodet',
        ),
    ]
