# Generated by Django 4.0.1 on 2022-02-16 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link', '0027_alter_ingreso_hijas_guia_madre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresorcp',
            fields=[
                ('ingreso_guias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='link.ingreso_guias')),
            ],
            options={
                'verbose_name_plural': 'Ingreso Recepciones',
            },
            bases=('link.ingreso_guias',),
        ),
    ]
