# Generated by Django 4.0.1 on 2022-04-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_productodet_guia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productodet',
        ),
    ]
