# Generated by Django 4.0.1 on 2022-04-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_productodet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodet',
            name='guia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='tests.test'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productodet',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='test',
            table='guias',
        ),
    ]
