# Generated by Django 4.0.1 on 2022-04-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_productodet_guia_alter_productodet_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodet',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='tests.test'),
        ),
        migrations.AlterModelTable(
            name='productodet',
            table='prod',
        ),
    ]
