# Generated by Django 4.0.1 on 2022-04-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0002_alter_impguias_numfin_alter_impguias_numini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Destinatario'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='destino',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Destino'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='dirdes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion Destinatario'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='munides',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='rutades',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='teldes',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='No. Telefono'),
        ),
    ]
