# Generated by Django 4.0.4 on 2022-05-09 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0004_alter_impguias_numfin_alter_impguias_numini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='numfin',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Numero Final'),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='numini',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Numero inicial'),
        ),
    ]
